# Import Libraries

In [92]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pickle

# Load the dataset

In [93]:
# load the dataset
data = pd.read_csv('/Users/macbookpro/Desktop/Heart Disease API Using Flask/heart_disease_data.csv')

In [94]:
# print first 5 rows of the dataset
data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [95]:
# drop the target column
X = data.drop(columns=['target'])
y = data['target']

In [96]:
# independent 
X

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

In [97]:
# dependent
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

# Data Splitting

In [98]:
# split the dataset into training & testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [99]:
# know the shape of the spliited data
print(y.shape, y_train.shape, y_test.shape)

(303,) (242,) (61,)

#### 303 => Data Points
#### 242 => Training Data
#### 61 => Testing Data

In [100]:
# scale the features using Standard Scaler
scaler = StandardScaler()

In [101]:
# scale the train data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Training

In [102]:
# train the model
model = LogisticRegression()

In [103]:
# fit the model based on scaled data
model.fit(X_train_scaled, y_train) # y => Target

LogisticRegression()

# Model Prediction

In [104]:
# prediction on training data
y_train_pred = model.predict(X_train_scaled)
accuracy = accuracy_score(y_train, y_train_pred) # y_test => True Labels ; y_pred => predicted labels
print("Training accuracy: ", round(accuracy))

Training accuracy:  1

In [105]:
# prediction on test data
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred) # y_test => True Labels ; y_pred => predicted labels
print("Testing accuracy: ", round(accuracy))

Testing accuracy:  1

# Save the Models

#### Scaler & Pickle File

In [106]:
# model file
with open('heart_disease_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

# scaler file
with open('heart_disease_scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

# Predictive System

In [107]:
import pickle
import numpy as np

# model file
with open('heart_disease_model.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

# scaler file
with open('heart_disease_scaler.pkl', 'rb') as scaler_file:
    loaded_scaler = pickle.load(scaler_file)

In [108]:
# input new data from the dataset
new_data_point = [63,1,3,145,233,1,0,150,0,2.3,0,0,1]
# transform the new data into a scaler
scaled_data = loaded_scaler.transform([new_data_point])

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [109]:
scaled_data

array([[ 0.95362125,  0.68313005,  2.04442042,  0.74027896, -0.24889401,
         2.47338777, -1.02899151, -0.0056522 , -0.71589105,  1.02021682,
        -2.28365678, -0.71469098, -2.21751422]])

# Make Predictions

In [111]:
# prediction on the scaled data
prediction = loaded_model.predict(scaled_data)
prediction

array([1])

In [112]:
print(prediction[0])

1

In [113]:
# conditional statement to check if a person has a heart disease or not
if prediction[0] == 1:
    print("This Person Has a Heart Disease")
else:
    print("This Person DOES NOT Have a Heart Disease")

This Person Has a Heart Disease

## 28:31